# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://www.erraticbits.ca/"
defaultContentLanguage = "en"
timeout = "10m"

enableRobotsTXT = true

summaryLength = 0

[pagination]
pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]
