languageCode = "en"
languageName = "English"
weight = 1

title = "Erraticbits"
# logo = "img/avatar-icon.png"
# description = "My awesome website"
copyright = ""

[params]
isoCode = "en"
displayName = "EN"
rtl = false
dateFormat = "2 January 2006"

