image: alpine/latest
oauth: pages.sr.ht/PAGES:RW
secrets:
- 7e266198-e44f-4acc-a6e5-9b845f3180c8
sources:
- git@git.sr.ht:~onewheelgeek/straybits.org
packages:
- hugo
- nodejs
environment:
  site: straybits.org
tasks:
- package: |
    cd $site
    hugo
    tar -C public -cvz . > ../site.tar.gz
- upload: |
    acurl -f https://pages.sr.ht/publish/$site \
        -Fcontent=@site.tar.gz 
