---
kind: pipeline
type: docker
name: default
trigger:
  branch:
    - master

steps:

- name: Build 
  image: plugins/hugo
  settings:
    hugo_version: 0.119.0
  commands:
  - apk add go 

- name: Minify
  image: alpine
  commands:
  - apk add minify 
  - minify -r -o public/ public/

- name: Upload 
  image: jguyomard/hugo-builder
  commands:
  - eval `ssh-agent -s`
  - echo "$SSH_KEY" | ssh-add -
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - rsync -rv -e "ssh -p 22" public/ $SSH_USER@$SSH_HOST:root --checksum
  environment:
    SSH_KEY:
      from_secret: SSH_KEY
    SSH_USER:
      from_secret: SSH_USER
    SSH_HOST:
      from_secret: SSH_HOST
      