stages:
  - build
  - deploy
  
build:
  stage:  build
  image: registry.gitlab.com/pages/hugo:latest
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
  - hugo version
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master

deploy:
  stage:  deploy
  image: alpine:latest
  before_script:
    - apk update && apk add openssh-client bash rsync
    - eval $(ssh-agent -s)
    - echo "192.168.30.11 caddy.home.adipose.net" >> /etc/hosts
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  environment:
    name: production
    url: jclement.ca
  script:
    - rsync -avz --delete -e "ssh" --progress public/ deploy_jclement@caddy.home.adipose.net:/var/www/test3.jclement.ca
  only:
    - master