baseurl = "https://www.straybits.org"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "straybits.org"
canonifyurls  = true

DefaultContentLanguage = "en"
theme = "jeff"
metaDataFormat = "yaml"
disqusShortname = "zeos-ca"
#googleAnalytics = "XXX"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = false

[BlackFriday]
  smartypants = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.tableOfContents]
    endLevel = 3
    startLevel = 1

[Params]
  subtitle = "Code. Privacy. Wood. Unicycles. Radio."
  readingTime = true
  hideAuthor = true
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  selfHosted = true
  rss = true
  comments = true
  #gcse = "002888195400749182309:cakccbp7nyf"

[[Params.bigimg]]
  src = "img/map.jpg"
  #desc = "Dark"
#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  #desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "OneWheelGeek"
  #email = "NA"
  #facebook = "username"
  #googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  #gitlab = "jeff"
  #github = "jclement"
  twitter = "OneWheelGeek"
  #reddit = "OneWheelGeek"
  #linkedin = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  mastodon = "onewheelgeek@mastodon.social"
  keybase = "jsc"


[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1


# [[menu.main]]
#     identifier = "samples"
#     name = "Samples"
#     weight = 2

# [[menu.main]]
#     parent = "samples"
#     name = "Big Image Sample"
#     url = "post/2017-03-07-bigimg-sample"
#     weight = 1

# [[menu.main]]
#     parent = "samples"
#     name = "Math Sample"
#     url = "post/2017-03-05-math-sample"
#     weight = 2

# [[menu.main]]
#     parent = "samples"
#     name = "Code Sample"
#     url = "post/2016-03-08-code-sample"
#     weight = 3

#[[menu.main]]
#    identifier = "projects"
#    name = "Projects"
#    weight = 2

[[menu.main]]
    identifier = "projects"
    name = "Projects"
    weight = 4

[[menu.main]]
    parent = "projects"
    name = "Werdz"
    url = "https://werdz.ca"
    weight = 1

[[menu.main]]
    identifier = "code"
    name = "Code"
    weight = 3

[[menu.main]]
    parent = "code"
    name = "Github"
    url = "https://github.com/jclement"
    weight = 2

[[menu.main]]
    parent = "code"
    name = "sr.ht"
    url = "https://git.sr.ht/~onewheelgeek/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 80

#[[menu.main]]
#    name = "Tags"
#    url = "tags"
#    weight = 90 

[[menu.main]]
    name = "Gemlog"
    url = "gemini://gemini.straybits.org"
    weight = 2