# fly.toml app configuration file generated for erratic-blog on 2023-09-08T16:04:07-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "erratic-blog"
primary_region = "yyz"

[build]

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
