name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.6.0
        with:
            hugo-version: latest # optional, default is latest
            extended: false # optional, default is false
      - name: Build
        run: hugo
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ERRATIC_BLOG }}'
          channelId: live
          projectId: erratic-blog
